package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alert generated by hbm2java
 */
public class Alert  implements java.io.Serializable {


     private Integer id;
     private Date alertDate;
     private String title;
     private String note;

    public Alert() {
    }

    public Alert(Date alertDate, String title, String note) {
       this.alertDate = alertDate;
       this.title = title;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getAlertDate() {
        return this.alertDate;
    }
    
    public void setAlertDate(Date alertDate) {
        this.alertDate = alertDate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


