package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String code;
     private String title;
     private Set courseSessions = new HashSet(0);
     private Set delegations = new HashSet(0);

    public Course() {
    }

	
    public Course(String code, String title) {
        this.code = code;
        this.title = title;
    }
    public Course(String code, String title, Set courseSessions, Set delegations) {
       this.code = code;
       this.title = title;
       this.courseSessions = courseSessions;
       this.delegations = delegations;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set courseSessions) {
        this.courseSessions = courseSessions;
    }
    public Set getDelegations() {
        return this.delegations;
    }
    
    public void setDelegations(Set delegations) {
        this.delegations = delegations;
    }




}


