package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Delegation generated by hbm2java
 */
public class Delegation  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Student student;
     private Date dateAssigned;

    public Delegation() {
    }

    public Delegation(Course course, Student student, Date dateAssigned) {
       this.course = course;
       this.student = student;
       this.dateAssigned = dateAssigned;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getDateAssigned() {
        return this.dateAssigned;
    }
    
    public void setDateAssigned(Date dateAssigned) {
        this.dateAssigned = dateAssigned;
    }




}


