package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detail generated by hbm2java
 */
public class Detail  implements java.io.Serializable {


     private String matricule;
     private Student student;
     private String homeTown;
     private String parentContact1;
     private String parentContact2;
     private Date dateOfBirth;
     private String note;

    public Detail() {
    }

	
    public Detail(Student student, String homeTown, String parentContact1, Date dateOfBirth) {
        this.student = student;
        this.homeTown = homeTown;
        this.parentContact1 = parentContact1;
        this.dateOfBirth = dateOfBirth;
    }
    public Detail(Student student, String homeTown, String parentContact1, String parentContact2, Date dateOfBirth, String note) {
       this.student = student;
       this.homeTown = homeTown;
       this.parentContact1 = parentContact1;
       this.parentContact2 = parentContact2;
       this.dateOfBirth = dateOfBirth;
       this.note = note;
    }
   
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getHomeTown() {
        return this.homeTown;
    }
    
    public void setHomeTown(String homeTown) {
        this.homeTown = homeTown;
    }
    public String getParentContact1() {
        return this.parentContact1;
    }
    
    public void setParentContact1(String parentContact1) {
        this.parentContact1 = parentContact1;
    }
    public String getParentContact2() {
        return this.parentContact2;
    }
    
    public void setParentContact2(String parentContact2) {
        this.parentContact2 = parentContact2;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


