package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer id;
     private String title;
     private Set students = new HashSet(0);
     private Set notices = new HashSet(0);
     private Set messages = new HashSet(0);

    public Group() {
    }

	
    public Group(String title) {
        this.title = title;
    }
    public Group(String title, Set students, Set notices, Set messages) {
       this.title = title;
       this.students = students;
       this.notices = notices;
       this.messages = messages;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getNotices() {
        return this.notices;
    }
    
    public void setNotices(Set notices) {
        this.notices = notices;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


