package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Instructor generated by hbm2java
 */
public class Instructor  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String phoneNumber;
     private String email;
     private Set courseSessions = new HashSet(0);

    public Instructor() {
    }

	
    public Instructor(String fname, String lname, String phoneNumber, String email) {
        this.fname = fname;
        this.lname = lname;
        this.phoneNumber = phoneNumber;
        this.email = email;
    }
    public Instructor(String fname, String lname, String phoneNumber, String email, Set courseSessions) {
       this.fname = fname;
       this.lname = lname;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.courseSessions = courseSessions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set courseSessions) {
        this.courseSessions = courseSessions;
    }




}


