package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1



/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer id;
     private Group group;
     private Student student;
     private String title;
     private String content;

    public Message() {
    }

	
    public Message(String title, String content) {
        this.title = title;
        this.content = content;
    }
    public Message(Group group, Student student, String title, String content) {
       this.group = group;
       this.student = student;
       this.title = title;
       this.content = content;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


