package cot.entities;
// Generated Mar 5, 2016 8:17:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice  implements java.io.Serializable {


     private Integer id;
     private Group group;
     private Date noticeDate;
     private String title;
     private String content;
     private String signedBy;
     private String status;

    public Notice() {
    }

    public Notice(Group group, Date noticeDate, String title, String content, String signedBy, String status) {
       this.group = group;
       this.noticeDate = noticeDate;
       this.title = title;
       this.content = content;
       this.signedBy = signedBy;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Date getNoticeDate() {
        return this.noticeDate;
    }
    
    public void setNoticeDate(Date noticeDate) {
        this.noticeDate = noticeDate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getSignedBy() {
        return this.signedBy;
    }
    
    public void setSignedBy(String signedBy) {
        this.signedBy = signedBy;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


